# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
#  param_fetcher_listener:  true
#  allowed_methods_listener:  true
  body_listener:
    enabled: true
  routing_loader:
    include_format: false
  view:
    view_response_listener:
      enabled: true #permet d'utiliser le retour sans faire appel à handleView
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
  format_listener:
    rules:
    - { path: ^/, prefer_extension: false, fallback_format: json, priorities: [ json ] }
